# Generated by Django 5.1 on 2024-09-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEntree', models.DateField()),
                ('qteInitiale', models.FloatField()),
                ('qteActuelle', models.FloatField()),
                ('dateExpiration', models.DateField()),
            ],
        ),
    ]
