# Generated by Django 5.1 on 2024-09-07 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_alter_detail_table'),
        ('produits', '0003_stock'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleName', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.category')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commandes.commande')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.fournisseur')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.stock')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
