# Generated by Django 5.1 on 2024-09-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_stock_table_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='article',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='entreprise_ptr',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
