# Generated by Django 5.1 on 2024-09-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('passWord', models.CharField(max_length=100)),
                ('isAdmin', models.BooleanField(default=False)),
                ('createdBy', models.IntegerField(null=True)),
                ('inscriptionDate', models.DateField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
    ]
