# Generated by Django 5.1 on 2024-09-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='createdBy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
