# Generated by Django 5.1 on 2024-09-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_representant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entreprise',
            table='entreprise',
        ),
        migrations.AlterModelTable(
            name='representant',
            table='representant',
        ),
    ]
