# Generated by Django 5.1 on 2024-09-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_alter_entreprise_table_alter_representant_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comptes.utilisateur')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
            ],
            bases=('comptes.utilisateur',),
        ),
    ]
