# Generated by Django 5.1 on 2024-09-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_alter_vendeur_table_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('statut', models.CharField(max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.contrat')),
            ],
            options={
                'db_table': 'local',
            },
        ),
    ]
