# Generated by Django 5.1 on 2024-09-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_remove_commande_client_remove_facture_commande_and_more'),
        ('comptes', '0008_local'),
        ('produits', '0005_remove_article_category_remove_article_commande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='contrat',
        ),
        migrations.RemoveField(
            model_name='representant',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='representant',
            name='utilisateur_ptr',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='utilisateur_ptr',
        ),
        migrations.DeleteModel(
            name='Contrat',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.DeleteModel(
            name='Entreprise',
        ),
        migrations.DeleteModel(
            name='Representant',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.DeleteModel(
            name='Vendeur',
        ),
    ]
