# Generated by Django 5.1 on 2024-09-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('entreprise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comptes.entreprise')),
                ('statut', models.CharField(choices=[('Regulier', 'REG'), ('Occasionnel', 'OCC')], default='F', max_length=20)),
                ('telephone_client', models.CharField(max_length=15)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'client',
            },
            bases=('comptes.entreprise',),
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('entreprise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comptes.entreprise')),
                ('actif', models.BooleanField(default=True)),
                ('isExternal', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fournisseur',
            },
            bases=('comptes.entreprise',),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEntree', models.DateField(auto_now_add=True)),
                ('qteInitiale', models.FloatField(default=100)),
                ('qteActuelle', models.FloatField(default=1)),
                ('dateExpiration', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.category'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCom', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('Initiée', 'INI'), ('En traitement', 'ENT'), ('Traitée', 'TTE'), ('Payée', 'PYE')], default='F', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commandes.client')),
            ],
            options={
                'db_table': 'commande',
            },
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.FloatField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commandes.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commandes.commande')),
            ],
            options={
                'db_table': 'detail',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commandes.fournisseur'),
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commandes.stock'),
        ),
    ]
