# Generated by Django 5.1 on 2024-09-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCom', models.DateField()),
                ('statut', models.CharField(max_length=50)),
                ('dateEcheance', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.client')),
            ],
            options={
                'db_table': 'commande',
            },
        ),
    ]
