# Generated by Django 5.1 on 2024-09-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateField()),
                ('dateEcheance', models.DateField()),
                ('isProformat', models.BooleanField(default=True)),
                ('statut', models.CharField(max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.commande')),
            ],
            options={
                'db_table': 'facture',
            },
        ),
    ]
