# Generated by Django 5.1 on 2024-09-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte', models.FloatField()),
                ('prixUnitaire', models.FloatField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.commande')),
            ],
        ),
    ]
