# Generated by Django 5.1 on 2024-09-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_detail_article'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detail',
            table='detail',
        ),
    ]
