# Generated by Django 5.1 on 2024-09-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_alter_detail_table'),
        ('produits', '0005_remove_article_category_remove_article_commande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='facture',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
